on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@master
        with:
          node-version: "13.x"
      - name: Ubuntu dependencies
        if: contains(matrix.os, 'ubuntu') 
        run: sudo apt-get install libgtk-3-dev
      - name: Build Qode binary
        run: node build.js
        env:
          SYNC_GIT_SUBMODULE: 1
      - name: Consolidate Windows release assets
        if: contains(matrix.os, 'windows')
        run: mkdir -p node/out/Release/qode-release && cp -rf node/out/Release/qode.exe node/out/Release/qode.exp node/out/Release/qode.lib node/out/Release/qode-release/
      - name: Consolidate Unix release 
        if: contains(matrix.os, 'windows') != true
        run: mkdir -p node/out/Release/qode-release && cp -rf node/out/Release/qode node/out/Release/qode-release/
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: gz
          GHR_PATH: node/out/Release/qode-release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
